# Generated by Django 5.2.6 on 2025-09-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=120, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('subject', models.CharField(max_length=120, verbose_name='Asunto')),
                ('message', models.TextField(max_length=2000, verbose_name='Mensaje')),
                ('terms', models.BooleanField(default=False, verbose_name='Aceptó términos')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP remitente')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
